'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Icon } from '@iconify/react';

export default function ExportPage() {
    const [exporting, setExporting] = useState(false);
    const [exported, setExported] = useState<string | null>(null);

    const generateCSV = () => {
        setExporting(true);

        // Sample data structure (would pull from actual data in production)
        const csvContent = [
            'Type,Date,Details,Notes',
            'Pregnancy,2024-12-04,"Due Date: 2025-06-15, Week: 20","Healthy pregnancy"',
            'Kick Session,2024-12-04,"10 kicks in 45 minutes",""',
            'Weight Log,2024-12-04,"65.5 kg, Week 20","On track"',
            'Symptom,2024-12-04,"Nausea, Severity: 3/5","Morning"',
            'Appointment,2024-12-15,"20-week ultrasound","Dr. Smith"',
        ].join('\n');

        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = `gestimate-export-${new Date().toISOString().split('T')[0]}.csv`;
        a.click();

        setExporting(false);
        setExported('csv');
        setTimeout(() => setExported(null), 3000);
    };

    const generateSummary = () => {
        setExporting(true);

        const summary = `
GESTIMATE PREGNANCY SUMMARY
===========================
Generated: ${new Date().toLocaleDateString()}

PREGNANCY DETAILS
-----------------
Calculation Method: LMP
Due Date: June 15, 2025
Current Week: 20 weeks, 3 days
Trimester: Second

HEALTH TRACKING SUMMARY
-----------------------
Kick Sessions: 15 total (avg 8 mins each)
Weight Progress: Started 60kg, Current 65.5kg (+5.5kg)
Symptoms Logged: 23 entries
Contractions: 0 sessions

MILESTONES
----------
Week 20: Baby is the size of a Banana
Development: Can taste flavors!

UPCOMING APPOINTMENTS
--------------------
Dec 15, 2024 - 20-week Anatomy Ultrasound
Jan 10, 2025 - Glucose Screening Test

HOSPITAL BAG
------------
Progress: 45% packed

---
Generated by Gestimate
Your Smart Pregnancy Companion
    `.trim();

        const blob = new Blob([summary], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = `gestimate-summary-${new Date().toISOString().split('T')[0]}.txt`;
        a.click();

        setExporting(false);
        setExported('summary');
        setTimeout(() => setExported(null), 3000);
    };

    return (
        <div className="min-h-screen py-12 px-4">
            <div className="max-w-lg mx-auto">
                <Link href="/app" className="text-purple-600 hover:underline mb-4 inline-block">← Back</Link>

                <div className="bg-white rounded-2xl shadow-xl p-8">
                    <div className="text-6xl text-center mb-4 text-gray-500 flex justify-center">
                        <Icon icon="solar:export-bold-duotone" />
                    </div>
                    <h1 className="text-3xl font-bold text-gray-900 text-center mb-2">Data Export</h1>
                    <p className="text-gray-600 text-center mb-8">Download your pregnancy data</p>

                    <div className="space-y-4">
                        {/* CSV Export */}
                        <div className="p-6 border-2 border-gray-200 rounded-xl">
                            <div className="flex items-center gap-4 mb-4">
                                <div className="text-4xl">📊</div>
                                <div>
                                    <h2 className="font-bold text-gray-900">CSV Export</h2>
                                    <p className="text-sm text-gray-600">Complete data in spreadsheet format</p>
                                </div>
                            </div>
                            <ul className="text-sm text-gray-600 mb-4 space-y-1">
                                <li>✓ All weight logs</li>
                                <li>✓ Kick session history</li>
                                <li>✓ Symptom records</li>
                                <li>✓ Appointments</li>
                            </ul>
                            <button
                                onClick={generateCSV}
                                disabled={exporting}
                                className="w-full bg-gradient-to-r from-blue-500 to-indigo-500 text-white font-bold py-3 rounded-xl hover:from-blue-600 hover:to-indigo-600 transition-all disabled:opacity-50"
                            >
                                {exported === 'csv' ? '✓ Downloaded!' : 'Download CSV'}
                            </button>
                        </div>

                        {/* Summary Export */}
                        <div className="p-6 border-2 border-gray-200 rounded-xl">
                            <div className="flex items-center gap-4 mb-4">
                                <div className="text-4xl">📝</div>
                                <div>
                                    <h2 className="font-bold text-gray-900">Pregnancy Summary</h2>
                                    <p className="text-sm text-gray-600">Quick overview for doctor visits</p>
                                </div>
                            </div>
                            <ul className="text-sm text-gray-600 mb-4 space-y-1">
                                <li>✓ Current pregnancy status</li>
                                <li>✓ Milestone summary</li>
                                <li>✓ Upcoming appointments</li>
                                <li>✓ Hospital bag progress</li>
                            </ul>
                            <button
                                onClick={generateSummary}
                                disabled={exporting}
                                className="w-full bg-gradient-to-r from-pink-500 to-purple-500 text-white font-bold py-3 rounded-xl hover:from-pink-600 hover:to-purple-600 transition-all disabled:opacity-50"
                            >
                                {exported === 'summary' ? '✓ Downloaded!' : 'Download Summary'}
                            </button>
                        </div>
                    </div>

                    {/* Info */}
                    <div className="mt-8 p-4 bg-blue-50 rounded-xl">
                        <h3 className="font-bold text-blue-800 mb-2">💡 Export Tips</h3>
                        <ul className="text-sm text-blue-700 space-y-1">
                            <li>• Share CSV with your doctor for detailed records</li>
                            <li>• Print summary for quick reference at appointments</li>
                            <li>• Your data is always yours to keep</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
}
