'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Icon } from '@iconify/react';

interface Preference {
    id: string;
    category: string;
    text: string;
    selected: boolean;
}

const BIRTH_PLAN_OPTIONS: Record<string, string[]> = {
    'Environment': [
        'Dim lighting',
        'Music playing',
        'Limited visitors during labor',
        'Partner present at all times',
        'Birthing ball available',
        'Freedom to move around',
    ],
    'Pain Management': [
        'Natural birth - no medication',
        'Epidural when needed',
        'IV pain medications',
        'Breathing techniques',
        'Water therapy (shower/tub)',
        'Massage/counter-pressure',
    ],
    'Labor': [
        'Eat/drink as tolerated',
        'Minimal cervical checks',
        'Intermittent fetal monitoring',
        'Avoid artificial oxytocin if possible',
        'No episiotomy unless necessary',
        'Delayed cord clamping',
    ],
    'After Birth': [
        'Immediate skin-to-skin contact',
        'Delay routine procedures for bonding',
        'Breastfeeding within first hour',
        'Rooming-in with baby',
        'Delayed bathing',
        'No pacifiers or bottles',
    ],
    'C-Section (if needed)': [
        'Partner in operating room',
        'Lower drape to see baby born',
        'Immediate skin-to-skin if possible',
        'Partner to accompany baby',
    ],
};

export default function BirthPlanPage() {
    const [preferences, setPreferences] = useState<Preference[]>(() => {
        const initial: Preference[] = [];
        Object.entries(BIRTH_PLAN_OPTIONS).forEach(([category, options]) => {
            options.forEach((text, idx) => {
                initial.push({ id: `${category}-${idx}`, category, text, selected: false });
            });
        });
        return initial;
    });
    const [notes, setNotes] = useState('');

    const togglePreference = (id: string) => {
        setPreferences(prev => prev.map(p =>
            p.id === id ? { ...p, selected: !p.selected } : p
        ));
    };

    const selectedCount = preferences.filter(p => p.selected).length;
    const categories = Object.keys(BIRTH_PLAN_OPTIONS);

    const exportPlan = () => {
        const selected = preferences.filter(p => p.selected);
        const grouped: Record<string, string[]> = {};

        selected.forEach(p => {
            if (!grouped[p.category]) grouped[p.category] = [];
            grouped[p.category].push(p.text);
        });

        let plan = `MY BIRTH PLAN\n${'='.repeat(40)}\n\n`;

        Object.entries(grouped).forEach(([category, items]) => {
            plan += `${category.toUpperCase()}\n${'-'.repeat(30)}\n`;
            items.forEach(item => {
                plan += `• ${item}\n`;
            });
            plan += '\n';
        });

        if (notes) {
            plan += `ADDITIONAL NOTES\n${'-'.repeat(30)}\n${notes}\n`;
        }

        plan += `\n${'='.repeat(40)}\nGenerated by Gestimate`;

        const blob = new Blob([plan], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'my-birth-plan.txt';
        a.click();
    };

    return (
        <div className="min-h-screen py-12 px-4">
            <div className="max-w-2xl mx-auto">
                <Link href="/app" className="text-purple-600 hover:underline mb-4 inline-block">← Back</Link>

                <div className="bg-white rounded-2xl shadow-xl p-8">
                    <div className="text-6xl text-center mb-4 text-teal-500 flex justify-center">
                        <Icon icon="solar:clipboard-list-bold-duotone" />
                    </div>
                    <h1 className="text-3xl font-bold text-gray-900 text-center mb-2">Birth Plan</h1>
                    <p className="text-gray-600 text-center mb-6">Document your preferences</p>

                    <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 mb-6">
                        <p className="text-yellow-800 text-sm">
                            💡 Your birth plan is a guide, not a contract. Flexibility is key as things may change during labor.
                        </p>
                    </div>

                    {/* Categories */}
                    <div className="space-y-6">
                        {categories.map(category => (
                            <div key={category}>
                                <h2 className="font-bold text-gray-800 mb-3 flex items-center gap-2">
                                    <Icon icon={
                                        category === 'Environment' ? 'solar:home-bold-duotone' :
                                            category === 'Pain Management' ? 'solar:medical-kit-bold-duotone' :
                                                category === 'Labor' ? 'solar:stopwatch-bold-duotone' :
                                                    category === 'After Birth' ? 'solar:heart-bold-duotone' :
                                                        'solar:hospital-bold-duotone'
                                    } className="text-purple-500" />
                                    {category}
                                </h2>
                                <div className="space-y-2">
                                    {preferences
                                        .filter(p => p.category === category)
                                        .map(pref => (
                                            <label
                                                key={pref.id}
                                                className={`flex items-center gap-3 p-3 rounded-lg cursor-pointer transition-all ${pref.selected ? 'bg-purple-50 border-2 border-purple-300' : 'bg-gray-50 hover:bg-gray-100'
                                                    }`}
                                            >
                                                <input
                                                    type="checkbox"
                                                    checked={pref.selected}
                                                    onChange={() => togglePreference(pref.id)}
                                                    className="w-5 h-5 rounded text-purple-500 focus:ring-purple-500"
                                                />
                                                <span className={pref.selected ? 'text-purple-700 font-medium' : 'text-gray-700'}>
                                                    {pref.text}
                                                </span>
                                            </label>
                                        ))}
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Additional Notes */}
                    <div className="mt-6">
                        <label className="block font-bold text-gray-800 mb-2">Additional Notes</label>
                        <textarea
                            value={notes}
                            onChange={(e) => setNotes(e.target.value)}
                            placeholder="Any other preferences or things your care team should know..."
                            className="w-full p-3 border-2 border-gray-200 rounded-xl focus:border-purple-500 focus:outline-none resize-none"
                            rows={4}
                        />
                    </div>

                    {/* Stats & Export */}
                    <div className="mt-6 flex items-center justify-between">
                        <div className="text-gray-600">
                            <span className="font-bold text-purple-700">{selectedCount}</span> preferences selected
                        </div>
                        <button
                            onClick={exportPlan}
                            disabled={selectedCount === 0}
                            className="bg-gradient-to-r from-pink-500 to-purple-500 text-white font-bold py-3 px-6 rounded-xl hover:from-pink-600 hover:to-purple-600 transition-all shadow-lg disabled:opacity-50"
                        >
                            📄 Export Plan
                        </button>
                    </div>
                </div>

                {/* Tips */}
                <div className="mt-8 bg-white rounded-2xl shadow-xl p-6">
                    <h2 className="font-bold text-gray-900 mb-3 flex items-center gap-2">
                        <Icon icon="solar:lightbulb-bold-duotone" className="text-yellow-500" />
                        Tips
                    </h2>
                    <ul className="text-sm text-gray-600 space-y-2">
                        <li>• Discuss your plan with your healthcare provider</li>
                        <li>• Share copies with your birth team</li>
                        <li>• Keep it to 1-2 pages for easy reference</li>
                        <li>• Review and update as your due date approaches</li>
                    </ul>
                </div>
            </div>
        </div>
    );
}
